name: ci

on:
  push:
    branches:
      - 'dev'
    tags:
      - 'v*'

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate build configuration
        uses: docker/build-push-action@v6
        with:
          call: check

      - name: Build and push
        uses: docker/build-push-action@v6
        if: github.ref_name != 'dev'
        with:
          push: true
          tags: |
            psaintelligence/superset-shillelagh-gristapi:latest
            psaintelligence/superset-shillelagh-gristapi:${{ github.ref_name }}

      - name: Build and push
        uses: docker/build-push-action@v6
        if: github.ref_name == 'dev'
        with:
          push: true
          tags: |
            psaintelligence/superset-shillelagh-gristapi:dev-${{ github.sha }}
